/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'bought' : IDL.Null }),
  'storeId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'quantity' : IDL.Text,
});
export const Store = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addShoppingItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addStore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteShoppingItem' : IDL.Func([IDL.Nat], [], []),
  'deleteStore' : IDL.Func([IDL.Nat], [], []),
  'getAllShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
  'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItemsByStore' : IDL.Func([IDL.Nat], [IDL.Vec(ShoppingItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateItemStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'pending' : IDL.Null, 'bought' : IDL.Null })],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'bought' : IDL.Null }),
    'storeId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'quantity' : IDL.Text,
  });
  const Store = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addShoppingItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addStore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteShoppingItem' : IDL.Func([IDL.Nat], [], []),
    'deleteStore' : IDL.Func([IDL.Nat], [], []),
    'getAllShoppingItems' : IDL.Func([], [IDL.Vec(ShoppingItem)], ['query']),
    'getAllStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItemsByStore' : IDL.Func([IDL.Nat], [IDL.Vec(ShoppingItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateItemStatus' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'pending' : IDL.Null, 'bought' : IDL.Null })],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };